const loginFields = [
  {
    labelText: 'Email address',
    labelFor: 'email-address',
    id: 'email-address',
    name: 'email',
    type: 'email',
    autoComplete: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    labelText: 'Password',
    labelFor: 'password',
    id: 'password',
    name: 'password',
    type: 'password',
    autoComplete: 'current-password',
    isRequired: true,
    placeholder: 'Password',
  },
];

const persoanlDetailsFields = [
  {
    labelText: 'Firstname',
    labelFor: 'firstname',
    id: 'firstname',
    name: 'firstname',
    type: 'text',
    autoComplete: 'firstname',
    isRequired: true,
    placeholder: 'Firstname',
  },
  {
    labelText: 'Lastname',
    labelFor: 'lastname',
    id: 'lastname',
    name: 'lastname',
    type: 'text',
    autoComplete: 'lastname',
    isRequired: true,
    placeholder: 'Lastname',
  },
  {
    labelText: 'Email address',
    labelFor: 'email-address',
    id: 'email-address',
    name: 'email',
    type: 'email',
    autoComplete: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    labelText: 'Phone',
    labelFor: 'phone',
    id: 'phone',
    name: 'phone',
    type: 'number',
    autoComplete: 'phone',
    isRequired: true,
    placeholder: 'Phone',
  },
  {
    labelText: 'Password',
    labelFor: 'password',
    id: 'password',
    name: 'password',
    type: 'password',
    autoComplete: 'password',
    isRequired: true,
    placeholder: 'Password',
  },
  {
    labelText: 'Confirm Password',
    labelFor: 'confirm-password',
    id: 'confirm-password',
    name: 'confirm-password',
    type: 'password',
    autoComplete: 'confirm-password',
    isRequired: true,
    placeholder: 'Confirm Password',
  },
];

const companyDetailsFields = [
  {
    labelText: 'Company name',
    labelFor: 'name',
    id: 'name',
    name: 'name',
    type: 'text',
    autoComplete: 'name',
    isRequired: true,
    placeholder: 'Company name',
  },
  {
    labelText: 'Company Email',
    labelFor: 'email',
    id: 'email',
    name: 'email',
    type: 'email',
    autoComplete: 'email',
    isRequired: true,
    placeholder: 'Company Email',
  },
  {
    labelText: 'Phone',
    labelFor: 'phone',
    id: 'phone',
    name: 'phone',
    type: 'number',
    autoComplete: 'phone',
    isRequired: true,
    placeholder: 'Company Phone',
  },
  {
    labelText: 'County',
    labelFor: 'country',
    id: 'country',
    name: 'country',
    type: 'text',
    autoComplete: 'country',
    isRequired: true,
    placeholder: 'County',
  },
  {
    labelText: 'City',
    labelFor: 'city',
    id: 'city',
    name: 'city',
    type: 'text',
    autoComplete: 'city',
    isRequired: true,
    placeholder: 'City',
  },
  {
    labelText: 'Address',
    labelFor: 'address',
    id: 'address',
    name: 'address',
    type: 'text',
    autoComplete: 'address',
    isRequired: true,
    placeholder: 'Address',
  },
];

export { loginFields, persoanlDetailsFields, companyDetailsFields };
