const loginFields = [
  {
    labelText: 'Email address',
    labelFor: 'email',
    id: 'email',
    name: 'email',
    type: 'email',
    autoComplete: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    labelText: 'Password',
    labelFor: 'password',
    id: 'password',
    name: 'password',
    type: 'password',
    autoComplete: 'current-password',
    isRequired: true,
    placeholder: 'Password',
  },
];

const persoanlDetailsFields = [
  {
    labelText: 'Firstname',
    labelFor: 'firstname',
    id: 'firstName',
    name: 'firstName',
    type: 'text',
    autoComplete: 'firstName',
    isRequired: true,
    placeholder: 'First name',
  },
  {
    labelText: 'Lastname',
    labelFor: 'lastName',
    id: 'lastName',
    name: 'lastName',
    type: 'text',
    autoComplete: 'lastName',
    isRequired: true,
    placeholder: 'Last name',
  },
  {
    labelText: 'Email address',
    labelFor: 'email-address',
    id: 'email',
    name: 'email',
    type: 'email',
    autoComplete: 'email',
    isRequired: true,
    placeholder: 'Email address',
  },
  {
    labelText: 'Phone',
    labelFor: 'phone',
    id: 'phone',
    name: 'phone',
    type: 'number',
    autoComplete: 'phone',
    isRequired: true,
    placeholder: 'Phone',
  },
  {
    labelText: 'Password',
    labelFor: 'password',
    id: 'password',
    name: 'password',
    type: 'password',
    autoComplete: 'password',
    isRequired: true,
    placeholder: 'Password',
  },
];

const companyDetailsFields = [
  {
    labelText: 'Company name',
    labelFor: 'name',
    id: 'name',
    name: 'name',
    type: 'text',
    autoComplete: 'name',
    isRequired: true,
    placeholder: 'Company name',
  },
  {
    labelText: 'Company Email',
    labelFor: 'orgEmail',
    id: 'orgEmail',
    name: 'orgEmail',
    type: 'email',
    autoComplete: 'orgEmail',
    isRequired: true,
    placeholder: 'Company email',
  },
  {
    labelText: 'Phone',
    labelFor: 'orgPhone',
    id: 'orgPhone',
    name: 'orgPhone',
    type: 'number',
    autoComplete: 'orgPhone',
    isRequired: true,
    placeholder: 'Company phone',
  },
  {
    labelText: 'County',
    labelFor: 'country',
    id: 'country',
    name: 'country',
    type: 'text',
    autoComplete: 'country',
    isRequired: true,
    placeholder: 'Country',
  },
  {
    labelText: 'City',
    labelFor: 'city',
    id: 'city',
    name: 'city',
    type: 'text',
    autoComplete: 'city',
    isRequired: true,
    placeholder: 'City',
  },
  {
    labelText: 'Address',
    labelFor: 'address',
    id: 'address',
    name: 'address',
    type: 'text',
    autoComplete: 'address',
    isRequired: true,
    placeholder: 'Address',
  },
];

export { loginFields, persoanlDetailsFields, companyDetailsFields };
